js_main:
    filters:
        - rjsmin
    type: js
    files:
        - bower_components/jquery/dist/jquery.min.js
        - bower_components/bootstrap/js/affix.js
        - bower_components/bootstrap/js/alert.js
        - bower_components/bootstrap/js/dropdown.js
        - bower_components/bootstrap/js/tooltip.js
        - bower_components/bootstrap/js/modal.js
        - bower_components/bootstrap/js/transition.js
        - bower_components/bootstrap/js/button.js
        - bower_components/bootstrap/js/popover.js
        - bower_components/bootstrap/js/carousel.js
        - bower_components/bootstrap/js/scrollspy.js
        - bower_components/bootstrap/js/collapse.js
        - bower_components/bootstrap/js/tab.js
        - scripts/main.js

styles_main:
    filters:
        - less
        - cssmin
    type: css
    files:
        - styles/main.less